repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --preview]
        exclude: "^(psi4/share/|psi4/driver/qcdb/|psi4/__init__.py|psi4/metadata.py|psi4/driver/__init__.py|samples/|tests/|doc/|devtools/|conda/)"
      - id: ruff-format
        exclude: "^(psi4/share/|psi4/driver/qcdb/|psi4/__init__.py|psi4/metadata.py|psi4/driver/__init__.py|samples/|tests/|doc/|devtools/|conda/)"
  - repo: https://github.com/doublify/pre-commit-clang-format.git
    rev: master
    hooks:
      - id: clang-format
